title: Counseling Space paz
description: 女性と子どものための相談機関です
url: "https://counselingspacepaz.com"
baseurl: "/paz-HP"

markdown: kramdown
destination: _site

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  - node_modules
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      og_image: /images/ogp/lavender-background.jpg
include:
  - assets
