# --------------------------------------
# _config.yml（Jekyll設定）
# --------------------------------------

# 相対パス崩れ防止
baseurl: ""

# デバッグ時：SWA標準URL
url: "https://icy-rock-024ded110.1.azurestaticapps.net"
# DNS切替後は本番URLに変更

# 静的資産を必ず含める
include:
  - assets
  - images
  - content
  - favicon.ico
  - robots.txt

# 出力先指定
destination: _site

# その他
markdown: kramdown
theme: minima
