name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build_deploy_prod:
    name: Build & Deploy (Production)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build
          ls -l _site/index.html

      - name: Upload to Azure Static Web Apps
        id: swa_deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "."           # リポジトリルート
          output_location: "_site"    # Jekyll生成物
          skip_app_build: true
