
name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_deploy_prod:
    name: Build & Deploy (Production)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          bundle install
        working-directory: ${{ github.workspace }} # ← ここを追記

      - name: Build Jekyll site
        run: bundle exec jekyll build
        working-directory: ${{ github.workspace }} # ← ここを追記

      - name: Upload to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "_site"
          skip_app_build: false
# ... (Build Jekyll site ステップの直後)

      - name: Build Jekyll site
        run: bundle exec jekyll build
        working-directory: ${{ github.workspace }}

      # --- ↓↓↓ Pages デプロイ用の追加ステップ ↓↓↓ ---

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site' # Jekyllのビルド成果物ディレクトリ

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# --- ↑↑↑ Pages デプロイ用の追加ステップ ↑↑↑ ---

      - name: Upload to Azure Static Web Apps
        id: deploy
# ... (以下 Azure SWA の設定が続きます)
