name: Build and Deploy Jekyll site to Azure Static Web Apps

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build_and_deploy:
    name: Build & Deploy (Production)
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"       # ✅ プロジェクトのルート（index.mdなどがある場所）
          output_location: "_site" # ✅ Jekyllの成果物フォルダ
          skip_app_build: true     # ✅ Actionsで既にビルド済み


