name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]   # mainブランチにPushで自動デプロイ
  workflow_dispatch:      # 手動実行も残す

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # ルートに index.html があるのでここは "/"
          app_location: "/"
          api_location: ""
          output_location: ""

          # Oryxを完全スキップ
          skip_app_build: true
          app_build_command: ""
