deploy_pages:
    name: 3. Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_site
    environment:
      name: github-pages
    steps:
      - name: Download built site artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site

      - name: Upload Pages-ready artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
