name: SWA Manual Deploy (Safe)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # リポジトリのルートに index.html がある前提
          app_location: "/"
          api_location: ""
          output_location: ""

          # ここが肝。Oryxによるビルドを抑止する
          skip_app_build: true
